server {
    listen 443 ssl;
    server_name api.diptrade.xpasha85.ru api.diptrade.ru;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    ssl_certificate /etc/letsencrypt/live/admin.diptrade.xpasha85.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.diptrade.xpasha85.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name api.diptrade.xpasha85.ru api.diptrade.ru;
    return 301 https://$host$request_uri;
}
